title: Anson Huang (he/him)
logo: /assets/img/headshot.JPG
google_analytics: UA-249313509-2
theme: jekyll-theme-minimal
github:
  is_user_page: true
  owner_url: https://github.com/ansonjhuang
  linkedin: https://www.linkedin.com/in/anson-j-huang/
  email: mailto:ansonh@cs.washington.edu
  resume: /assets/resume.pdf
